# fly.toml app configuration file generated for alphagenome-green-frog-72 on 2025-09-19T11:13:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alphagenome-green-frog-72'
primary_region = 'bos'

[experimental]
  memory = "1gb"
  cpu = "1"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "python manage.py migrate"

[env]
  ALPHAGENOME_API_KEY = 'AIzaSyC66joDkyeHyqMXIGjSYcpUK8Midtn1JeM'
  FLASK_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'gencode_split'
  destination = '/app/gencode_split'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
